### ISSUE TITLE
RX8025?

### ISSUE THREAD

**Issue by bob-u** [Wh1teRabbitHU/RX8010SJ#1]
Thanks for sharing this.  Having build in resonator, I see RX8010SJ RTC as a great alternative to most cheap RTCs (like PCF8563 or MCP79400) that require external crystal, matching caps, guard ring using up PCB real-estate and increasing part count.  BTW, it appears cheap ebay DS3231 are mostly fake now: https://blog.heypete.com/2017/07/29/a-look-inside-the-ds3231-real-time-clock/rt

I do wonder if RX8025 could be used with RX8010SJ library as well?  It is 40c more but has temperature compensated XO and could be closer in accuracy to (real) DS3231.

**Comment by Wh1teRabbitHU** [comment]
First of all, sorry for the delayed response, for some unknown reasons, I don't get any notifications when I receive requests.

And to answer to your question:
Well, it depends on the register addresses but it should make sense to have a similar map for the IC. There are 3 possibilities:
- Addresses are matching and both chip has the same function list. In this case, you don't need to do anything
- Addresses are different, but has the same function list. (alert for example) To make it work, you have to update the macro-s in the header file and it will work.
- New function or different function with a different address map: Well in this case you have to implement the difference manually.

I found this datasheet, it's a good starting point to check those functions that you are interested in: https://support.epson.biz/td/api/doc_check.php?dl=app_RX-8025SA&lang=en

Search for the register table section. (8.2.1) It seems like your unit has an 0x10 offset compared to mine. It can still work if the RX8025 ignore the first byte. (You have to check it) If not, just manually update the addresses, and it should work. I would help you implement/upgrade the code, but I cannot test it, because I don't have that version of ic in my inventory. If you are interested in using this other chip, then you should copy my solution and adjust the source according to the datasheet. It shouldn't take a huge effort to make it work

**Comment by Wh1teRabbitHU** [comment]
I'm closing this issue, let me know if you have any update on this topic
